### PR TITLE
fix: cast of int-to-(number) when int is boolean (#596)

### LINKED ISSUE #596: Invalid casts among primitive types
Hi, in some cases casts are invalid. For example in class ``` com/paypal/android/foundation/presentation/model/ConsentUriParams.java ``` type ``` boolean ``` is converted to ``` byte ``` using explicit cast
```java
    public void writeToParcel(android.os.Parcel parcel, int i) {
        parcel.writeByte((byte) this.showConsent);
        parcel.writeByte((byte) this.showOneTouch);
```
but the following code should be generated instead
```java
    public void writeToParcel(android.os.Parcel parcel, int i) {
        parcel.writeByte(this.showConsent ? 1 : 0);
        parcel.writeByte(this.showOneTouch ? 1 : 0);
```
APK: https://drive.google.com/file/d/16O--dtXt35zB1Ahx-9qEYvCmyeF1n0AG/view?usp=sharing

### PR DESCRIPTION
**Pull request by asashour**
Fixes #596 

Please merge #601 first, since it is already included.

### CODE REVIEW

File: jadx-core/src/main/java/jadx/core/dex/instructions/args/InsnArg.java [hunk 1]
```diff
@@ -122,6 +132,32 @@ public InsnArg wrapInstruction(InsnNode insn) {
 		return arg;
 	}
 
+	private InsnArg processCast(InsnNode insn, int i) {
```
Comment (skylot) [inline jadx-core/src/main/java/jadx/core/dex/instructions/args/InsnArg.java]: Move this code to `ModVisitor`

File: jadx-core/src/main/java/jadx/core/dex/visitors/ModVisitor.java [hunk 2]
```diff
@@ -155,6 +159,22 @@ private static void replaceStep(MethodNode mth, InsnRemover remover) {
...
+								InsnArg zero = new LiteralArg(0, ArgType.BYTE);
+								InsnArg one = new LiteralArg(1, ArgType.BYTE);
+								IfNode ifNode = new IfNode(IfOp.NE, -1, InsnArg.wrapArg(pi), LiteralArg.FALSE);
+								IfCondition condition = IfCondition.fromIfNode(ifNode);
+								TernaryInsn ternary = new TernaryInsn(condition, insn.getResult(), one, zero);
+								replaceInsn(block, i, ternary);
+								remover.addAndUnbind(pi);
+							}
+						}
+						break;
```
Comment (skylot) [inline jadx-core/src/main/java/jadx/core/dex/visitors/ModVisitor.java]: I don't know why you need previous instruction, try to limit modification scope to minimum.
So I can suggest do this:
```java
					case CAST:
						// replace boolean to byte cast with ternary
						if (insn.getResult().getType() == ArgType.BYTE
								&& insn.getArg(0).getType() == ArgType.BOOLEAN) {
							IfNode ifNode = new IfNode(IfOp.EQ, -1, insn.getArg(0), LiteralArg.TRUE);
							IfCondition condition = IfCondition.fromIfNode(ifNode);
							InsnArg zero = InsnArg.lit(0, ArgType.BYTE);
							InsnArg one = InsnArg.lit(1, ArgType.BYTE);
							TernaryInsn ternary = new TernaryInsn(condition, insn.getResult(), one, zero);
							replaceInsn(block, i, ternary);
						}
						break;
```

**Comment by sergey-wowwow** [comment]
@asashour @skylot 
I would also recommend to do the same for boolean -> int casts, because such cases are also generated by a wrong way

File: jadx-core/src/main/java/jadx/core/dex/visitors/ModVisitor.java (hunk 2 above)
Comment (asashour) [reply jadx-core/src/main/java/jadx/core/dex/visitors/ModVisitor.java]: Sure, this is much better, I guess I was distracted by the "previous Instruction" in the previous code location.

**Comment by asashour** [comment]
> I would also recommend to do the same for boolean -> int casts, because such cases are also generated by a wrong way

I thought about `int-to-char`, `int-to-short`, but I guess there is no boolean to int cases [here](http://pallergabor.uw.hu/androidblog/dalvik_opcodes.html), I would try to make some test cases and fix them in other PRs.

I am not experienced in davlik, so appreciate if you can provide some tests.

File: jadx-core/src/main/java/jadx/core/dex/visitors/ModVisitor.java (hunk 2 above)
Comment (asashour) [reply jadx-core/src/main/java/jadx/core/dex/visitors/ModVisitor.java]: Also, should we just use `.isPrimitive()`, instead of the `BYTE||CHAR||SHORT||LONG||DOUBLE||FLOAT`, or even remove it completely, since no casting can be done except to these things (`VOID||BOOLEAN` are the remaining in `primitive`).

Comment (skylot) [reply jadx-core/src/main/java/jadx/core/dex/visitors/ModVisitor.java]: You can use  `.isPrimitive()` I think it is ok.
But for me looks like you overdid this ))
Yeah sure, you can write these weird conversions in smali but I don't think we can find all of them in real APKs.
Anyway I think this is good work, thanks!
