### PR TITLE
fix(gui): editor theme loading and error/fallback handling improved

### LINKED ISSUE #1476: java.lang.NullPointerException: Cannot invoke "org.fife.ui.rsyntaxtextarea.Theme.apply(org.fife.ui.rsyntaxtextarea.RSyntaxTextArea)" because the return value of "jadx.gui.ui.MainWindow.getEditorTheme()" is null
Please describe what you did before the error occurred.
**IMPORTANT!** If the error occurs with a specific APK file please attach or provide link to apk file!
 * Jadx version: 1.3.4
* Java version: 18.0.1
* Java VM: Oracle Corporation Java HotSpot(TM) 64-Bit Server VM
* Platform: Windows 10 (10.0 amd64)
* Max heap size: 4096 MB
* Program args: -Xms168m -Xmx4096m -Dawt.useSystemAAFontSettings=lcd -Dswing.aatext=true -XX:+UseG1GC

```
java.lang.NullPointerException: Cannot invoke "org.fife.ui.rsyntaxtextarea.Theme.apply(org.fife.ui.rsyntaxtextarea.RSyntaxTextArea)" because the return value of "jadx.gui.ui.MainWindow.getEditorTheme()" is null
	at jadx.gui.ui.codearea.AbstractCodeArea.loadCommonSettings(AbstractCodeArea.java:249)
	at jadx.gui.ui.codearea.AbstractCodeArea.getDefaultArea(AbstractCodeArea.java:243)
	at jadx.gui.ui.dialog.LogViewerDialog.initUI(LogViewerDialog.java:52)
	at jadx.gui.ui.dialog.LogViewerDialog.<init>(LogViewerDialog.java:46)
	at jadx.gui.ui.dialog.LogViewerDialog.openWithLevel(LogViewerDialog.java:41)
	at jadx.gui.ui.dialog.LogViewerDialog.open(LogViewerDialog.java:36)
	at jadx.gui.ui.MainWindow$19.actionPerformed(MainWindow.java:1010)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1029)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1073)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6616)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
	at java.desktop/java.awt.Component.processEvent(Component.java:6381)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4991)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4823)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4823)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

### PR DESCRIPTION
**Pull request by jpstotz**
This PR should fix #1476.

After calling `MainWindow.setEditorTheme` once `MainWindow.editorTheme` always should contain a non-null value. 

First call of `setEditorTheme` is done by `loadSettings`. Assuming an exception is thrown before so that `setEditorTheme` is never called also means that initialization of MainWindow fails, so there should be no UI and state of `editorTheme` field is no longer relevant.

### CODE REVIEW

File: jadx-gui/src/main/java/jadx/gui/ui/MainWindow.java [hunk 1]
```diff
@@ -1298,15 +1301,32 @@ public void setLocationAndPosition() {
...
+			if (Files.isRegularFile(themePath)) {
+				try (InputStream is = Files.newInputStream(themePath)) {
+					editorTheme = Theme.load(is);
+					return;
+				}
+			}
+		} catch (Exception e) {
+			LOG.error("Failed to load editor theme: {}", editorThemePath, e);
+		}
+		LOG.warn("Falling back to default editor theme", editorThemePath);
```
Comment (skylot) [inline jadx-gui/src/main/java/jadx/gui/ui/MainWindow.java:1322]:
```suggestion
		LOG.warn("Falling back to default editor theme: {}", editorThemePath);
```

**Review by skylot — APPROVED** [review]

**Comment by skylot** [comment]
@jpstotz thanks :+1:
