### PR TITLE
fix: forward navigation shortcut on macOS

### LINKED ISSUE #1297: forward hot key seems not work in macos[feature]
*Describe your idea:*
image

it doesn't work

### PR DESCRIPTION
**Pull request by Surendrajat**
### Description

This PR fixes the issue of `nav.forward` shortcut not working on macOS.

closes #1297

### CODE REVIEW

**Review by skylot — APPROVED** [review]

**Comment by skylot** [comment]
@Surendrajat thanks! Looks good to me.
I will wait a couple of days for confirming that issue is fixed. 
Hope @stAticasd (#1297) will check and reply.

**Comment by Surendrajat** [comment]
@skylot yeah.. Waiting a bit will probably be better. I do hope that it doesn't break this for other OSes tho.

**Comment by stAticasd** [comment]
@Surendrajat Thank you!Looks good to me

**Comment by skylot** [comment]
> I do hope that it doesn't break this for other OSes tho.

@Surendrajat we can replace added `true` arg with `SystemInfo.IS_MAC` and not affect other OSes.

File: jadx-gui/src/main/java/jadx/gui/ui/MainWindow.java [hunk 1]
```diff
@@ -948,7 +948,7 @@ public void actionPerformed(ActionEvent e) {
 			}
 		};
 		forwardAction.putValue(Action.SHORT_DESCRIPTION, NLS.str("nav.forward"));
-		forwardAction.putValue(Action.ACCELERATOR_KEY, getKeyStroke(KeyEvent.VK_RIGHT, KeyEvent.ALT_DOWN_MASK));
+		forwardAction.putValue(Action.ACCELERATOR_KEY, getKeyStroke(KeyEvent.VK_RIGHT, KeyEvent.ALT_DOWN_MASK, true));
```
Comment (Surendrajat) [inline jadx-gui/src/main/java/jadx/gui/ui/MainWindow.java:951]: @skylot good idea.

```suggestion
		forwardAction.putValue(Action.ACCELERATOR_KEY, getKeyStroke(KeyEvent.VK_RIGHT, KeyEvent.ALT_DOWN_MASK, SystemInfo.IS_MAC));
```
