### PR TITLE
fix: loading aar/jar files (#631)

### LINKED ISSUE #631: Support for (specific?) AAR files
I found out that this commit:

SHA-1: 79ccaadaff18de7443491dbc333e71cfa6e3e3d5
* fix: handle big .jar files (using multi-dex option) (#390) (PR #568)

breaks decompilation for AAR libraries that I use. The result is that when loading those libraries into jadx, after a split-second it shows just empty "Source code" folder.

Unfortunately I cannot share with you the specific AARs. Is there any other way I can contribute to fixing this?

### PR DESCRIPTION
**Pull request by asashour**
By overwriting the created temp file

Fix #631

### CODE REVIEW

File: jadx-core/src/main/java/jadx/core/utils/files/InputFile.java [hunk 1]
```diff
@@ -134,7 +135,7 @@ private boolean loadFromZip(String ext) throws IOException, DecodeException {
 							case ".jar":
 								index++;
 								Path jarFile = Files.createTempFile(entryName, ".jar");
```
Comment (skylot) [inline jadx-core/src/main/java/jadx/core/utils/files/InputFile.java]: I just notice that in previous commits you replace many calls from `FileUtils.createTempFile` to `Files.createTempFile` and now temp files not deleted on exit and pollute temp dir, because `FileUtils.createTempFile`  invoke `file.deleteOnExit();` to remove temp file, but now it is not :(
Also names was nice like starting with `jadx-tmp-` so it easier to understard which app created it:
```
before: /tmp/jadx-tmp-8207354968595972366-classes.jar
after: /tmp/classes.jar8207354968595972366.jar
```
So, please, next time try to not change current behavior heavily, because sometimes it is hard to notice such changes on review :((

Comment (asashour) [reply jadx-core/src/main/java/jadx/core/utils/files/InputFile.java]: You are right, I have a bad habit of mixing multiple changes.

I thought using the new API would be better.

A new PR is underway.
